language: ruby
rvm:
- 2.6.2
install:
- bundle install
before_script:
- cp config/database.sample.yml config/database.yml
- sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
- sudo service postgresql restart
- sudo psql -c "create database mission_us_test;" -U postgres
script:
- rails db:migrate RAILS_ENV=test
- bundle exec rails
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
services:
- postgresql
branches:
  only:
    - master
