language: ruby
rvm:
- 2.6.2
install:
- bundle install
before_script:
- cp config/database.sample.yml config/database.yml
- sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/10/main/postgresql.conf
- sudo service postgresql restart
- sudo psql -c "create database mission_us_test;" -U postgres
script:
- rails db:migrate RAILS_ENV=test
- bundle exec rails
addons:
  postgresql: '10'
  apt:
    packages:
    - postgresql-10
    - postgresql-client-10
env:
  global:
  - PGPORT=5433
services:
- postgresql
branches:
  only:
    - master
