language: ruby
install:
- bundle install
before_script:
- cp config/database.sample.yml config/database.yml
- psql -c "create database mini_test;" -U postgres
script:
- bin/rake db:migrate RAILS_ENV=test
- bundle exec rake
addons:
  postgresql: '9.6'
env:
  global:
  - PGPORT=5433
services:
- postgresql
branches:
  only:
    - master
