default: &default
  adapter: postgresql
  encoding: unicode
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRESQL_USERNAME'] || 'postgres' %>
  password: <%= ENV['POSTGRESQL_PASSWORD'] || 'postgres' %>
  host: <%= ENV['POSTGRESQL_HOST'] || 'localhost' %>

development:
  <<: *default
  port: <%= ENV['POSTGRESQL_PORT'] || 5432 %>
  database: mini_development

test:
  <<: *default
  encoding: utf8
  database: mini_test

production:
  <<: *default
  database: mini_production
  username: manager_internal_network_internet
  password: <%= ENV['POSTGRESQL_PASSWORD'] %>
